import './globals.css'
import { Inter } from 'next/font/google'
import Cursor from '@/components/Cursor'
import TopButton from '@/components/TopButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mon Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <div>
            <Cursor/>
            <TopButton/>
          </div>
          {children}
        </>
      </body>
    </html>
  )
}
